import argparse

from grrmlog_parser.core import parse

parser = argparse.ArgumentParser()
parser.add_argument("path", help="path to the target log top")
args = parser.parse_args()

path = args.path

map = parse(path)

print(map)
print(map.eq_list[0])
print("eqs", len(map.eq_list))
print("pts", len(map.pt_list))
print("tss", len(map.ts_list))

print(map.atom_name)
print(map.initxyz)
print(map.fname_top_abs)
print(map.fname_top_rel)
print(map.natoms)
print(map.lowest_energy)
print(map.highest_energy)
print(map.neq)
print(map.nts)
print(map.npt)
print(map.jobtime)
print(map.universal_gamma)
print(map.infile)
print(map.scpathpara)
print(map.jobtype)
print(map.pathtype)
print(map.nobondrearrange)
print(map.siml_temperature_kelvin)
print(map.siml_pressure_atm)
print(map.energyshiftvalue_au)
print(map.level)
print(map.spinmulti)
print(map.totalcharge)
print(map.jobstatus)
print(map.jobmessage)
print(map.ngradient)
print(map.nhessian)
print(map.elapsedtime_sec)

eq0 = map.eq_list[0]
print("id", eq0.id)
print("category", eq0.category)
print("symmetry", eq0.symmetry)
print("xyz", eq0.xyz)
print("energy", eq0.energy)
print("gradient", eq0.gradient)
print("s2_value", eq0.s2_value)
print("dipole", eq0.dipole)
print("comment", eq0.comment)
print("electronic_energy_au", eq0.electronic_energy_au)
print("hess_eigenvalue_au", eq0.hess_eigenvalue_au)

edge0 = map.pt_list[0]
print("id", edge0.id)
print("category", edge0.category)
print("symmetry", edge0.symmetry)
print("comment", edge0.comment)
print("xyz", edge0.xyz)
print("gradient", edge0.gradient)
print("energy", edge0.energy)
print("s2_value", edge0.s2_value)
print("dipole", edge0.dipole)
print("electronic_energy_au", edge0.electronic_energy_au)
print("hess_eigenvalue_au", edge0.hess_eigenvalue_au)
print("pathdata", edge0.pathdata)
print("connection", edge0.connection)
